server:
  port: 8082

spring:
  profiles:
    active: qa

---

spring:
  profiles: development
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message:
    config: >>> Welcome to another Spring Boot Application! <<<

---

spring:
  profiles: qa
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp-qa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message:
    config: >>> Welcome to another Spring Boot Application! <<<

---

spring:
  profiles: prod
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:dcbapp-prod
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message:
    config: >>> Welcome to another Spring Boot Application! <<<